# Generated by Django 3.2 on 2021-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='person',
            new_name='created_person',
        ),
    ]
