# Generated by Django 3.2.2 on 2021-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_number',
            field=models.FloatField(choices=[(1, '1'), (1.5, '1+'), (1.75, '-2'), (2, '2'), (2.5, '2+'), (2.75, '-3'), (3, '3'), (3.5, '3+'), (3.75, '-4'), (4, '4'), (4.5, '4+'), (4.75, '-5'), (5, '5'), (5.5, '5+'), (5.75, '-6'), (6, '6')]),
        ),
    ]
