# Generated by Django 3.2 on 2021-05-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_person_post_created_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
