# Generated by Django 3.2.2 on 2021-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mark_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='mark_name',
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_number',
            field=models.IntegerField(choices=[(1, '1'), (1.5, '1+'), (2, '2'), (2.5, '2+'), (3, '3'), (3.5, '3+'), (4, '4'), (4.5, '4+'), (5, '5'), (5.5, '5+'), (6, '6')]),
        ),
    ]
