# Generated by Django 3.2.2 on 2021-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210513_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
