# Generated by Django 3.2.2 on 2021-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homework_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
    ]
