# Generated by Django 3.2.2 on 2021-05-26 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210526_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
