# Generated by Django 3.2.2 on 2021-05-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mark_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classroom'),
        ),
    ]
