# Generated by Django 3.2.2 on 2021-05-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
    ]
