# Generated by Django 3.2.2 on 2021-05-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mark_created_person'),
        ('dashboard', '0002_remove_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classroom'),
        ),
    ]
