# Generated by Django 3.2.2 on 2021-05-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_lesson_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lessonplan'),
        ),
    ]
