# Generated by Django 3.2.2 on 2021-05-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mark_created_person'),
        ('dashboard', '0005_auto_20210531_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='lessonplan',
            new_name='lesson_plan',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hour_finish',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='hour_start',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
