# Generated by Django 3.2.2 on 2021-05-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_lesson_lesson_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lessonplan'),
        ),
    ]
