# Generated by Django 3.2.2 on 2021-10-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_mark_created_person'),
        ('dashboard', '0009_auto_20211011_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.classroom')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
